rvm:
    - "1.8.7"
    - "1.9.3-p551"
    - "2.0.0-p598"
    - "2.1.5"
    - "2.2.0"
    - "jruby-1.7.19"
env:
    # Sadly, Travis seems to have a version of SQLite < 3.7.11 installed on many of its workers;
    # this prevents activerecord-import from working, since those versions of the SQLite engine
    # don't have support for multi-row inserts in a single statement. There really isn't anything
    # we can do about this, unfortunately..
    - LOW_CARD_TABLES_AR_TEST_VERSION=3.0.20 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=mysql
    - LOW_CARD_TABLES_AR_TEST_VERSION=3.0.20 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=postgres
    - LOW_CARD_TABLES_AR_TEST_VERSION=3.0.20 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=sqlite
    - LOW_CARD_TABLES_AR_TEST_VERSION=3.1.12 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=mysql
    - LOW_CARD_TABLES_AR_TEST_VERSION=3.1.12 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=postgres
    - LOW_CARD_TABLES_AR_TEST_VERSION=3.1.12 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=sqlite
    - LOW_CARD_TABLES_AR_TEST_VERSION=3.2.21 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=mysql
    - LOW_CARD_TABLES_AR_TEST_VERSION=3.2.21 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=postgres
    - LOW_CARD_TABLES_AR_TEST_VERSION=3.2.21 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=sqlite
    - LOW_CARD_TABLES_AR_TEST_VERSION=4.0.13 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=mysql
    - LOW_CARD_TABLES_AR_TEST_VERSION=4.0.13 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=postgres
    - LOW_CARD_TABLES_AR_TEST_VERSION=4.0.13 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=sqlite
    - LOW_CARD_TABLES_AR_TEST_VERSION=4.1.9 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=mysql
    - LOW_CARD_TABLES_AR_TEST_VERSION=4.1.9 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=postgres
    - LOW_CARD_TABLES_AR_TEST_VERSION=4.1.9 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=sqlite
    - LOW_CARD_TABLES_AR_TEST_VERSION=4.2.0 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=mysql
    - LOW_CARD_TABLES_AR_TEST_VERSION=4.2.0 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=postgres
    - LOW_CARD_TABLES_AR_TEST_VERSION=4.2.0 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=sqlite
before_script:
    - export JRUBY_OPTS="-J-Xmx256m -J-Xms256m $JRUBY_OPTS"
    - mysql -e 'create database myapp_test;'
    - psql -c 'create database myapp_test;' -U postgres
matrix:
    exclude:
        # ActiveRecord 4.x doesn't support Ruby 1.8.7
        -   rvm: 1.8.7
            env: LOW_CARD_TABLES_AR_TEST_VERSION=4.0.13 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=mysql
        -   rvm: 1.8.7
            env: LOW_CARD_TABLES_AR_TEST_VERSION=4.0.13 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=postgres
        -   rvm: 1.8.7
            env: LOW_CARD_TABLES_AR_TEST_VERSION=4.0.13 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=sqlite
        -   rvm: 1.8.7
            env: LOW_CARD_TABLES_AR_TEST_VERSION=4.1.9 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=mysql
        -   rvm: 1.8.7
            env: LOW_CARD_TABLES_AR_TEST_VERSION=4.1.9 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=postgres
        -   rvm: 1.8.7
            env: LOW_CARD_TABLES_AR_TEST_VERSION=4.1.9 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=sqlite
        -   rvm: 1.8.7
            env: LOW_CARD_TABLES_AR_TEST_VERSION=4.2.0 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=mysql
        -   rvm: 1.8.7
            env: LOW_CARD_TABLES_AR_TEST_VERSION=4.2.0 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=postgres
        -   rvm: 1.8.7
            env: LOW_CARD_TABLES_AR_TEST_VERSION=4.2.0 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=sqlite
        # There's a bug in ActiveRecord 3.1.x that makes it incompatible with Ruby 2.x
        -   rvm: 2.0.0
            env: LOW_CARD_TABLES_AR_TEST_VERSION=3.1.12 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=mysql
        -   rvm: 2.0.0
            env: LOW_CARD_TABLES_AR_TEST_VERSION=3.1.12 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=postgres
        -   rvm: 2.0.0
            env: LOW_CARD_TABLES_AR_TEST_VERSION=3.1.12 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=sqlite
        -   rvm: 2.1.2
            env: LOW_CARD_TABLES_AR_TEST_VERSION=3.1.12 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=mysql
        -   rvm: 2.1.2
            env: LOW_CARD_TABLES_AR_TEST_VERSION=3.1.12 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=postgres
        -   rvm: 2.1.2
            env: LOW_CARD_TABLES_AR_TEST_VERSION=3.1.12 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=sqlite
        # The activerecord-import gem currently doesn't support JRuby JDBC adapters with anything but MySQL
        # -   rvm: jruby-1.7.15
        #     env: LOW_CARD_TABLES_AR_TEST_VERSION=3.0.20 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=postgres
        # -   rvm: jruby-1.7.15
        #     env: LOW_CARD_TABLES_AR_TEST_VERSION=3.1.12 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=postgres
        # -   rvm: jruby-1.7.15
        #     env: LOW_CARD_TABLES_AR_TEST_VERSION=3.2.21 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=postgres
        # -   rvm: jruby-1.7.15
        #     env: LOW_CARD_TABLES_AR_TEST_VERSION=4.0.13 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=postgres
        # -   rvm: jruby-1.7.15
        #     env: LOW_CARD_TABLES_AR_TEST_VERSION=4.1.9 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=postgres
        # -   rvm: jruby-1.7.15
        #     env: LOW_CARD_TABLES_AR_TEST_VERSION=3.0.20 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=sqlite
        # -   rvm: jruby-1.7.15
        #     env: LOW_CARD_TABLES_AR_TEST_VERSION=3.1.12 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=sqlite
        # -   rvm: jruby-1.7.15
        #     env: LOW_CARD_TABLES_AR_TEST_VERSION=3.2.21 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=sqlite
        # -   rvm: jruby-1.7.15
        #     env: LOW_CARD_TABLES_AR_TEST_VERSION=4.0.13 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=sqlite
        # -   rvm: jruby-1.7.15
        #     env: LOW_CARD_TABLES_AR_TEST_VERSION=4.1.9 LOW_CARD_TABLES_TRAVIS_CI_DATABASE_TYPE=sqlite
